---

- name: Install dependencies
  apt:
    name: [
      python,
      curl,
      apt-transport-https,
      ca-certificates,
      gnupg2,
      software-properties-common,
    ]
    state: present

- name: remove old docker
  apt:
    name: [
      docker,
      docker-engine,
      docker.io,
    ]
    state: absent

- name: extra packages for Ubuntu
  apt:
    name: linux-image-extra-virtual
    state: present
  when: ansible_distribution == "Ubuntu"

- name: add key id
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present

- name: add docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} stable"
    filename: docker
    state: present

- name: install docker
  apt:
    name: docker-ce
    update_cache: yes
    state: present

- name: install pip
  shell: curl -sSL https://bootstrap.pypa.io/get-pip.py | python

- name: install docker-py and docker-compose
  pip:
    name: [
      docker-py,
      docker-compose,
    ]
    state: present