---
- name: Create NFS directory
  file:
    path: /var/nfs/usersdata
    state: directory
    owner: nobody
    group: nogroup
    mode: 666

- name: Install NFS necessary packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - nfs-kernel-server
    - nfs-common

- name: Copy NFS exports file
  copy:
    src: exports
    dest: '/etc/exports'
    owner: root
    group: root
    mode: 644
  notify: reload nfs
