---
- name: Install dependencies
  apt:
    name: [
      python3,
      curl,
      apt-transport-https,
      ca-certificates,
      gnupg2,
      software-properties-common,
      python3-pip,
    ]
    update_cache: yes
    state: present

- name: Install podman repo
  shell: echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
- name: Install podman key
  shell: curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/Release.key | sudo apt-key add

- name: Install podman
  apt:
    name: [
      podman,
    ]
    update_cache: yes
    state: present

- name: install docker-py, kubernetes and docker-compose
  pip:
    name: [
      kubernetes,
    ]
    state: present

- name: Upgrade all packages
  ansible.builtin.apt:
    name: '*'
    state: latest
    update_cache: true
