---
- name: Install docker and dependencies
  include: "os_family/{{ ansible_os_family }}.yml"

#- name: Reboot a slow machine that might have lots of updates to apply
#  ansible.builtin.reboot:
#    reboot_timeout: 3600

