---
- name: Install docker and dependencies
  include: "os_family/{{ ansible_os_family }}.yml"

- name: Configure docker
  include: "configuration.yml"
  when: ansible_facts['os_family'] == 'Debian'

#- name: Reboot a slow machine that might have lots of updates to apply
#  ansible.builtin.reboot:
#    reboot_timeout: 3600

