---
- name: Install minikube
  hosts: minikube
  remote_user: kaas
  become: true
  roles:
    - docker
    - kubectl
    - minikube

- name: Install kaas
  hosts: minikube
  remote_user: kaas
  become: true
  roles:
    - helm
    - kaas
