kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-share-pvc
  namespace: kaas
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi