---
- name: Install docker and dependencies
  include: "os_family/{{ ansible_os_family }}.yml"

- name: Copy jupyterhub config file
  copy:
    src: jupyterhub-config.yaml
    dest: '/home/{{ ansible_user }}/jupyterhub-config.yaml'

- name: Deploy Jupyterhub from url with 30 min wait
  become: no
  kubernetes.core.helm:
    timeout: 30m0s
    wait: true
    name: kaas
    chart_ref: "https://jupyterhub.github.io/helm-chart/jupyterhub-2.0.0.tgz"
    create_namespace: true
    release_namespace: kaas
    release_state: present
    values_files: /home/{{ ansible_user }}/jupyterhub-config.yaml
    kubeconfig: /home/{{ ansible_user }}/.kube/config

#- name: Wait for kaas kubernetes dashboard to start.
#  local_action: 
#    module: wait_for
#    host: "{{ ansible_host }}"
#    port: "30081"
#    delay: 10
#    timeout: 1800
#    state: started
#    msg: "Kubernetes Dashboard port 30081 PORT is not Listening"

#- name: Wait for kaas Jupyterhub dashboard to start.
#  local_action: 
#    module: wait_for
#    host: "{{ ansible_host }}"
#    port: "30080"
#    delay: 10
#    timeout: 1800
#    state: started
#    msg: "KaaS Junpyterhub Dashboard port 30080 PORT is not Listening"
  