---
- name: Copy jupyterhub config file
  copy:
    src: jupyterhub-config.yaml
    dest: '/home/vagrant/jupyterhub-config.yaml'

- name: Copy storage config file
  copy:
    src: kaas-storage.yaml
    dest: '/home/vagrant/kaas-storage.yaml'

- name: Apply storage manifest to the cluster.
  become: false
  kubernetes.core.k8s:
    state: present
    src: /home/vagrant/kaas-storage.yaml

- name: Copy PV config file
  copy:
    src: kaas-pv.yaml
    dest: '/home/vagrant/kaas-pv.yaml'

- name: Apply pv manifest to the cluster.
  become: false
  kubernetes.core.k8s:
    state: present
    src: /home/vagrant/kaas-pv.yaml

- name: Copy pvc config file
  copy:
    src: kaas-pvc.yaml
    dest: '/home/vagrant/kaas-pvc.yaml'

- name: Deploy Jupyterhub from url with 45 min wait
  kubernetes.core.helm:
    timeout: 15m0s
    wait: true
    name: kaas
    chart_ref: "https://jupyterhub.github.io/helm-chart/jupyterhub-2.0.0.tgz"
    create_namespace: true
    release_namespace: kaas
    release_state: present
    values_files: /home/vagrant/jupyterhub-config.yaml
    kubeconfig: /home/vagrant/.kube/config