---
- name: Copy jupyterhub config file
  copy:
    src: jupyterhub-config.yaml
    dest: '/home/vagrant/jupyterhub-config.yaml'

#- name: JHDB Copy storage config file
#  copy:
#    src: kaas-storage.yaml
#    dest: '/home/vagrant/kaas-storage.yaml'

#- name: JHDB Apply storage manifest to the cluster.
#  become: false
#  kubernetes.core.k8s:
#    state: present
#    src: /home/vagrant/kaas-storage.yaml

#- name: JHDB Copy PV config file
#  copy:
#    src: kaas-pv.yaml
#    dest: '/home/vagrant/kaas-pv.yaml'

#- name: JHDB Apply pv manifest to the cluster.
#  become: false
#  kubernetes.core.k8s:
#    state: present
#    src: /home/vagrant/kaas-pv.yaml

#- name: JHDB Copy pvc config file
#  copy:
#    src: kaas-pvc.yaml
#    dest: '/home/vagrant/kaas-pvc.yaml'

#- name: USER Copy user PV config file
#  copy:
#    src: kaas-users-pv.yaml
#    dest: '/home/vagrant/kaas-users-pv.yaml'

#- name: USER Apply pv manifest to the cluster.
#  become: false
#  kubernetes.core.k8s:
#    state: present
#    src: /home/vagrant/kaas-users-pv.yaml

#- name: USER Copy user PVC config file
#  copy:
#    src: kaas-users-pvc.yaml
#    dest: '/home/vagrant/kaas-users-pvc.yaml'

- name: Deploy Jupyterhub from url with 45 min wait
  kubernetes.core.helm:
    timeout: 15m0s
    wait: true
    name: kaas
    chart_ref: "https://jupyterhub.github.io/helm-chart/jupyterhub-2.0.0.tgz"
    create_namespace: true
    release_namespace: kaas
    release_state: present
    values_files: /home/vagrant/jupyterhub-config.yaml
    kubeconfig: /home/vagrant/.kube/config

#- name: USER Apply user pvc manifest to the cluster.
#  become: false
#  kubernetes.core.k8s:
#    state: present
#    src: /home/vagrant/kaas-users-pvc.yaml