---
# Create a ext4 filesystem on /dev/sdb and check disk blocks.
#- filesystem:
#    fstype: ext4
#    dev: /dev/sdb
#    opts: -cc

#- name: Create a directory if it does not exist
#  ansible.builtin.file:
#    cd rolespath: /mnt/local-storage
#    state: directory
#    mode: '0755'

#- name: Mount and bind volume
#  mount:
#  path: /mnt/local-storage
#  src: /dev/sdb
#  state: mounted

- copy:
    src: jupyterhub-config.yaml
    dest: '/home/vagrant/jupyterhub-config.yaml'

- copy:
    src: kaas-storage.yaml
    dest: '/home/vagrant/kaas-storage.yaml'

- name: Apply storage manifest to the cluster.
  become: false
  kubernetes.core.k8s:
    state: present
    src: /home/vagrant/kaas-storage.yaml

- copy:
    src: kaas-pv.yaml
    dest: '/home/vagrant/kaas-pv.yaml'

- name: Apply pv manifest to the cluster.
  become: false
  kubernetes.core.k8s:
    state: present
    src: /home/vagrant/kaas-pv.yaml

- copy:
    src: kaas-pvc.yaml
    dest: '/home/vagrant/kaas-pvc.yaml'

- name: Apply pvc manifest to the cluster.
  become: false
  kubernetes.core.k8s:
    state: present
    src: /home/vagrant/kaas-pvc.yaml

- name: Deploy Jupyterhub from url with 45 min wait
  kubernetes.core.helm:
    timeout: 45m0s
    wait: true
    name: kaas
    chart_ref: "https://jupyterhub.github.io/helm-chart/jupyterhub-2.0.0.tgz"
    create_namespace: true
    release_namespace: kaas
    release_state: present
    values_files: /home/vagrant/jupyterhub-config.yaml
    kubeconfig: /home/vagrant/.kube/config